import { useEffect, useMemo, useRef, useState } from 'react'
import * as XLSX from 'xlsx'
import { AlertTriangle, Archive, CalendarCheck, Check, ChevronLeft, ChevronRight, Clock3, Download, Expand, FileSpreadsheet, Filter, History, Import, Info, ListFilter, Menu, MoreVertical, Plus, RotateCcw, Search, Settings, SlidersHorizontal, Trash2, X } from 'lucide-react'

const seed = [
  {id:'7-29974',pv:7,number:29974,client:'DEL VALLE JAQUELINA',fantasy:'',delivery:'2026-07-13',product:'Gran Formato',work:'Archivo 1: Martina XV\nTipo: Vinilo de corte plateado\nTamaño: 11 x 6 cm\nCopias: 76\nDetalle: van en vertical porque es para vasos',total:69200,status:'Pendiente',priority:'urgente',user:'BRUNO',origin:'manual',created:'2026-07-07'},
  {id:'7-29305',pv:7,number:29305,client:'CLAA RODRIGO',fantasy:'Imprenta Pulser',delivery:'2026-07-14',product:'Gran Formato',work:'Archivo 1: El Rincón\nTipo: Vinilo Inflex\nImpresion: UV CMYK\nBase: Gris\nTamaño: 151 x 61 cm\nDetalle: Carpeta 18/06/26 de tarde',total:18050,status:'En proceso',priority:'normal',user:'LEONEL',origin:'excel',created:'2026-06-18'},
  {id:'7-29103',pv:7,number:29103,client:'CLAA RODRIGO',fantasy:'Imprenta Pulser',delivery:'2026-07-18',product:'Gran Formato',work:'Archivo 1: Arq Agus Eggs\nTipo: Vinilo Clear UV W + Corte Blanco INFLEX\nImpresion: UV CMYK W V\nTamaño: 123 x 122 cm\n\nArchivo 2: 1ro Mayo PLAZAS\nTipo: Vinilo Inflex\nImpresion: UV CMYK W V\nBase: Gris\nTamaño: 202 x 144 cm\n\nArchivo 3: Calcos 1ro Mayo\nTipo: Clear\nImpresion: UV CMYK WV\nTamaño: 5 x 5,7 cm\nCopias: 50 + 50\nDetalle: Corte profundo',total:9310,status:'Falta información',priority:'alta',user:'LEONEL',origin:'excel',created:'2026-06-16'}
]
const excelEpoch = n => new Date(Date.UTC(1899,11,30)+Number(n)*86400000).toISOString().slice(0,10)
const normalize = s => String(s??'').trim().replace(/_x000D_/g,'').replace(/\r/g,'')
const parseBlocks = work => normalize(work).split(/\n\s*\n|(?=Archivo\s+\d+\s*:)/i).map(s=>s.trim()).filter(Boolean)
const field = (text,label) => text.match(new RegExp(`${label}\\s*:\\s*([^\\n]+)`,'i'))?.[1]?.trim() || ''
const processType = job => {
  const product = normalize(job.product).toLowerCase()
  if (/eco\s*solvente|ecosolvente/.test(product)) return {id:'eco',label:'Eco Solvente'}
  if (/impresi[oó]n\s*uv|\buv\b/.test(product)) return {id:'uv',label:'Impresión UV'}
  return {id:'gran-formato',label:'Gran Formato'}
}
const money = new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0})
const fmtDate = value => value ? new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'short'}).format(new Date(`${value}T12:00:00`)) : 'Sin fecha'

function SlideToFinish({onDone}) {
  const [value,setValue]=useState(0); const done=useRef(false)
  const finish=()=>{if(done.current)return;done.current=true;setValue(100);setTimeout(onDone,180)}
  return <div className="slide-finish" style={{'--slide':`${value}%`}}>
    <div className="slide-fill"/><span>{value>80?'Soltá para finalizar':'Deslizá para finalizar'}</span><Check size={17}/>
    <input aria-label="Deslizar para finalizar orden" type="range" min="0" max="100" value={value} onChange={e=>setValue(+e.target.value)} onMouseUp={()=>value>82?finish():setValue(0)} onTouchEnd={()=>value>82?finish():setValue(0)} onKeyUp={e=>{if(e.key==='End'||value>82)finish()}} />
  </div>
}

function SlideToClear({onDone}) {
  const [value,setValue]=useState(0); const done=useRef(false)
  const finish=()=>{if(done.current)return;done.current=true;setValue(100);setTimeout(onDone,220)}
  const release=()=>value>88?finish():setValue(0)
  return <div className="slide-clear" style={{'--slide':`${value}%`}}>
    <div className="slide-clear-fill"/>
    <Trash2 size={18}/><span>{value>88?'Soltá para borrar todo':'Deslizá para limpiar todo'}</span>
    <input aria-label="Deslizar para limpiar todos los trabajos" type="range" min="0" max="100" value={value} onChange={e=>setValue(+e.target.value)} onMouseUp={release} onTouchEnd={release} onKeyUp={e=>{if(e.key==='End'||value>88)finish()}} />
  </div>
}

function Card({job,onFinish,onAction,onOpen}){
  const blocks=parseBlocks(job.work), first=blocks[0]||job.work, overdue=job.delivery<new Date().toISOString().slice(0,10), process=processType(job)
  return <article className={`job-card priority-${job.priority} process-${process.id}`}>
    <div className="card-top"><span className="order">Nº {job.number}</span><span className={`process-badge ${process.id}`}>{process.label}</span><button className="icon" onClick={()=>onAction(job)} aria-label="Menú de la orden"><MoreVertical/></button></div>
    <div className="client"><small>CLIENTE</small><h2>{job.client}</h2>{job.fantasy&&<p>{job.fantasy}</p>}</div>
    <div className="due"><span className={overdue?'late':''}><Clock3 size={15}/>{overdue?'Atrasado · ':''}{fmtDate(job.delivery)}</span><b>{job.status}</b></div>
    <div className="job-copy"><span className="material">{field(first,'Tipo')||job.product}</span><h3>{field(first,'Archivo 1')||field(first,'Archivo 2')||'Trabajo de producción'}</h3><p>{field(first,'Impresion')||field(first,'Impresión')}{field(first,'Tamaño')&&` · ${field(first,'Tamaño')}`}</p>{field(first,'Detalle')&&<p className="detail">{field(first,'Detalle')}</p>}</div>
    <button className="internal" onClick={()=>onOpen(job)}><span><b>{blocks.length}</b> {blocks.length===1?'trabajo interno':'trabajos internos'}</span><ChevronRight size={18}/></button>
    <SlideToFinish onDone={()=>onFinish(job.id)}/>
  </article>
}

function MenuDrawer({open,onClose,onNavigate,counts,lastImport,onClearAll}){
  useEffect(()=>{if(!open)return;const esc=e=>e.key==='Escape'&&onClose();document.addEventListener('keydown',esc);document.body.classList.add('locked');return()=>{document.removeEventListener('keydown',esc);document.body.classList.remove('locked')}},[open,onClose])
  const sections=[['PRODUCCIÓN',[['Panel de producción','panel',SlidersHorizontal],['Agregar trabajo','manual',Plus],['Importar Excel','import',Import],['Terminados hoy','completed',CalendarCheck,counts.completed],['Trabajos atrasados','overdue',AlertTriangle,counts.overdue]]],['CONSULTA',[['Buscar trabajo','search',Search],['Historial','history',History]]],['VISTA DEL PANEL',[['Filtrar panel','filter',Filter,counts.filters],['Ordenar tarjetas','sort',ListFilter],['Modo de visualización','presentation',Expand],['Pantalla completa','fullscreen',Expand]]],['SISTEMA',[['Última importación','lastImport',Info],['Configuración','settings',Settings]]]]
  return <><div className={`overlay ${open?'show':''}`} onClick={onClose}/><aside className={`drawer ${open?'open':''}`} aria-hidden={!open}><div className="drawer-head"><div><small>ROJAS IMPRESIONES</small><h2>Menú principal</h2></div><button className="icon" onClick={onClose} aria-label="Cerrar menú"><X/></button></div><div className="drawer-scroll">{sections.map(([title,items])=><section className="menu-section" key={title}><h3>{title}</h3>{items.map(([label,id,Icon,badge])=><button key={id} onClick={()=>{onNavigate(id);onClose()}}><Icon size={20}/><span>{label}</span>{badge>0&&<b>{badge}</b>}<ChevronRight size={17}/></button>)}</section>)}{lastImport&&<div className="import-note"><FileSpreadsheet/><span><small>ÚLTIMA IMPORTACIÓN</small><b>{lastImport.name}</b><em>{lastImport.imported} órdenes · {lastImport.sheet}</em></span></div>}<section className="danger-zone"><small>ZONA DE SEGURIDAD</small><p>Elimina todas las órdenes activas y terminadas de este dispositivo.</p><SlideToClear onDone={onClearAll}/></section><button className="logout" onClick={()=>alert('La autenticación todavía no está activada.')}><Archive size={19}/> Cerrar sesión</button></div></aside></>
}

function Modal({title,onClose,children,wide=false}){useEffect(()=>{const f=e=>e.key==='Escape'&&onClose();document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f)},[onClose]);return <div className="modal-wrap" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={`modal ${wide?'wide':''}`}><header><div><small>GESTIÓN DE PRODUCCIÓN</small><h2>{title}</h2></div><button className="icon" onClick={onClose}><X/></button></header><div className="modal-content">{children}</div></div></div>}

export function App(){
  const [jobs,setJobs]=useState(()=>JSON.parse(localStorage.getItem('rojas-jobs')||'null')||seed),[completed,setCompleted]=useState(()=>JSON.parse(localStorage.getItem('rojas-completed')||'[]')),[menu,setMenu]=useState(false),[view,setView]=useState('panel'),[selected,setSelected]=useState(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('delivery'),[lastImport,setLastImport]=useState(()=>JSON.parse(localStorage.getItem('rojas-import')||'null')),[toast,setToast]=useState('')
  useEffect(()=>localStorage.setItem('rojas-jobs',JSON.stringify(jobs)),[jobs]);useEffect(()=>localStorage.setItem('rojas-completed',JSON.stringify(completed)),[completed]);useEffect(()=>{if(lastImport)localStorage.setItem('rojas-import',JSON.stringify(lastImport))},[lastImport])
  const finish=id=>{const j=jobs.find(x=>x.id===id);setJobs(x=>x.filter(y=>y.id!==id));setCompleted(x=>[{...j,finishedAt:new Date().toISOString()},...x]);setToast(`Orden Nº ${j.number} finalizada`);setTimeout(()=>setToast(''),2500)}
  const visible=useMemo(()=>jobs.filter(j=>{const q=search.toLowerCase();const match=!q||`${j.number} ${j.client} ${j.fantasy} ${j.work}`.toLowerCase().includes(q);const today=new Date().toISOString().slice(0,10);return match&&(filter==='all'||filter==='overdue'&&j.delivery<today||filter==='urgent'&&j.priority==='urgente'||j.status===filter)}).sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),undefined,{numeric:true})),[jobs,search,filter,sort])
  const navigate=id=>{if(id==='fullscreen'){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();return}if(id==='search'){setSearch(' ');setView('panel');setTimeout(()=>document.querySelector('.search-input')?.focus(),50);return}if(id==='presentation'){document.body.classList.toggle('presentation');setView('panel');return}setView(id)}
  const importExcel=async file=>{const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array',cellDates:false}),sheetName=wb.SheetNames[0],rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,defval:''}),hi=rows.findIndex(r=>r.some(c=>normalize(c).toLowerCase()==='número')),headers=rows[hi].map(normalize),objects=rows.slice(hi+1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]]))),mapped=objects.map(r=>({id:String(r.Número),number:r.Número,client:normalize(r.Cliente),fantasy:normalize(r['Nombre Fantasia']),delivery:excelEpoch(r['Fecha Entrega']),product:normalize(r.Producto),work:normalize(r.Trabajo),total:Number(r.Total)||0,status:'Pendiente',priority:'normal',user:normalize(r.Usuario),origin:'excel',created:excelEpoch(r.Fecha)})),existing=new Set(jobs.map(j=>String(j.number))),fresh=mapped.filter(j=>!existing.has(String(j.number)));setJobs(x=>[...fresh,...x]);setLastImport({name:file.name,sheet:sheetName,read:mapped.length,imported:fresh.length,duplicates:mapped.length-fresh.length,date:new Date().toISOString()});setToast(`${fresh.length} órdenes importadas`);setView('panel')}
  const counts={completed:completed.filter(j=>j.finishedAt.slice(0,10)===new Date().toISOString().slice(0,10)).length,overdue:jobs.filter(j=>j.delivery<new Date().toISOString().slice(0,10)).length,filters:filter==='all'?0:1}
  const clearAll=()=>{setJobs([]);setCompleted([]);setMenu(false);setView('panel');setSearch('');setFilter('all');setToast('Se limpiaron todas las órdenes');setTimeout(()=>setToast(''),2500)}
  return <div className="app"><header className="topbar"><div className="brand"><img src="/logo-rojas.png"/><span><b>Producción</b><small>Gran formato · En vivo</small></span></div><div className="top-stats"><span><b>{jobs.length}</b> activas</span><span className="danger"><b>{counts.overdue}</b> atrasadas</span><span><b>{counts.completed}</b> terminadas hoy</span></div><button className="hamburger" onClick={()=>setMenu(true)} aria-label="Abrir menú principal"><Menu/><span>Menú</span>{counts.filters>0&&<i>{counts.filters}</i>}</button></header>
  <main><section className="board-head"><div><p>PLANTA DE PRODUCCIÓN</p><h1>Trabajos activos</h1><span>Actualizado ahora · {new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span></div><div className="board-tools"><label><Search/><input className="search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Orden, cliente, archivo…"/></label><button onClick={()=>setView('filter')}><Filter/>{filter==='all'?'Filtrar':filter}<ChevronRight/></button></div></section>
  {view==='panel'&&<><div className="active-row"><b>{visible.length} órdenes en pantalla</b><span>Ordenadas por {sort==='delivery'?'fecha de entrega':sort}</span></div><section className="grid">{visible.map(j=><Card key={j.id} job={j} onFinish={finish} onOpen={setSelected} onAction={setSelected}/>)}{!visible.length&&<div className="empty"><CalendarCheck/><h2>No hay trabajos para mostrar</h2><p>Probá limpiar la búsqueda o los filtros activos.</p><button onClick={()=>{setSearch('');setFilter('all')}}>Limpiar filtros</button></div>}</section></>}
  {view==='import'&&<ImportView onImport={importExcel} last={lastImport}/>} {view==='completed'&&<Completed jobs={completed} restore={j=>{setCompleted(x=>x.filter(y=>y.id!==j.id));setJobs(x=>[j,...x])}}/>} {view==='history'&&<HistoryView active={jobs} completed={completed}/>} {view==='overdue'&&<Overdue jobs={jobs.filter(j=>j.delivery<new Date().toISOString().slice(0,10))} finish={finish}/>} {view==='manual'&&<Manual onAdd={j=>{setJobs(x=>[j,...x]);setView('panel')}}/>} {view==='settings'&&<SettingsView/>}
  </main><MenuDrawer open={menu} onClose={()=>setMenu(false)} onNavigate={navigate} counts={counts} lastImport={lastImport} onClearAll={clearAll}/>{selected&&<Detail job={selected} onClose={()=>setSelected(null)} onFinish={()=>{finish(selected.id);setSelected(null)}}/>}{['filter','sort','lastImport'].includes(view)&&<QuickPanel mode={view} filter={filter} setFilter={v=>{setFilter(v);setView('panel')}} sort={sort} setSort={v=>{setSort(v);setView('panel')}} last={lastImport} close={()=>setView('panel')}/>} {toast&&<div className="toast"><Check/>{toast}</div>}</div>
}

function ImportView({onImport,last}){const [drag,setDrag]=useState(false);return <section className="page-card"><div className="page-title"><FileSpreadsheet/><div><h2>Importar Excel</h2><p>Compatible con la exportación del sistema administrativo. Detecta hoja y encabezados automáticamente.</p></div></div><label className={`drop ${drag?'drag':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);onImport(e.dataTransfer.files[0])}}><Import/><h3>Arrastrá el archivo Excel acá</h3><p>o hacé clic para seleccionarlo</p><span>Admite .xlsx y .xls · los duplicados no se vuelven a cargar</span><input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files[0]&&onImport(e.target.files[0])}/></label>{last&&<div className="last-box"><b>Última importación</b><span>{last.name} · {last.imported} importadas · {last.duplicates} duplicadas</span></div>}</section>}
function Completed({jobs,restore}){return <ListPage icon={CalendarCheck} title="Terminados hoy" subtitle="Órdenes cerradas durante la jornada">{jobs.map(j=><div className="list-row" key={j.id}><b>Nº {j.number}</b><span>{j.client}</span><span>{parseBlocks(j.work).length} trabajos</span><span>{new Date(j.finishedAt).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}</span><button onClick={()=>restore(j)}><RotateCcw/>Restaurar</button></div>)}</ListPage>}
function HistoryView({active,completed}){return <ListPage icon={History} title="Historial" subtitle="Consulta unificada de órdenes activas y finalizadas">{[...active,...completed].map(j=><div className="list-row" key={`${j.id}-${j.finishedAt||''}`}><b>Nº {j.number}</b><span>{j.client}</span><span>{j.product}</span><span>{j.finishedAt?'Finalizada':j.status}</span><em>{j.origin}</em></div>)}</ListPage>}
function Overdue({jobs,finish}){return <ListPage icon={AlertTriangle} title="Trabajos atrasados" subtitle="Conservan su fecha de entrega original">{jobs.map(j=><div className="list-row" key={j.id}><b>Nº {j.number}</b><span>{j.client}</span><span>{fmtDate(j.delivery)}</span><span>{j.status}</span><button onClick={()=>finish(j.id)}>Finalizar</button></div>)}</ListPage>}
function ListPage({icon:Icon,title,subtitle,children}){return <section className="page-card"><div className="page-title"><Icon/><div><h2>{title}</h2><p>{subtitle}</p></div></div><div className="list">{children}</div></section>}
function Manual({onAdd}){const [f,setF]=useState({number:'',client:'',fantasy:'',delivery:'',product:'Gran Formato',work:'',priority:'normal',status:'Pendiente'});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <section className="page-card"><div className="page-title"><Plus/><div><h2>Agregar trabajo manual</h2><p>Creá una orden sin importar un archivo.</p></div></div><div className="form-grid">{[['Número de orden','number'],['Cliente','client'],['Nombre de fantasía','fantasy'],['Fecha de entrega','delivery','date'],['Producto','product']].map(([l,k,t])=><label key={k}>{l}<input type={t||'text'} value={f[k]} onChange={e=>set(k,e.target.value)}/></label>)}<label>Prioridad<select value={f.priority} onChange={e=>set('priority',e.target.value)}><option>normal</option><option>alta</option><option>urgente</option></select></label><label>Estado<select value={f.status} onChange={e=>set('status',e.target.value)}><option>Pendiente</option><option>En proceso</option><option>Falta información</option></select></label><label className="full">Descripción / trabajos internos<textarea value={f.work} onChange={e=>set('work',e.target.value)} placeholder="Archivo 1: ...&#10;Tipo: ...&#10;Impresion: ...&#10;Tamaño: ..."/></label></div><button className="primary" disabled={!f.number||!f.client||!f.work} onClick={()=>onAdd({...f,id:String(f.number),total:0,user:'',origin:'manual',created:new Date().toISOString().slice(0,10)})}>Agregar al panel</button></section>}
function SettingsView(){return <section className="page-card"><div className="page-title"><Settings/><div><h2>Configuración</h2><p>Preferencias guardadas en este dispositivo.</p></div></div><div className="settings-grid">{['Materiales y alias','Procesos e impresión','Apariencia del panel','Reglas de importación','Modo presentación','Colores y prioridades'].map(x=><button key={x} onClick={()=>alert(`${x}: configuración disponible en la próxima edición administrativa.`)}><Settings/><b>{x}</b><ChevronRight/></button>)}</div></section>}
function Detail({job,onClose,onFinish}){return <Modal title={`Orden Nº ${job.number}`} onClose={onClose} wide><div className="detail-head"><div><small>CLIENTE</small><h2>{job.client}</h2><p>{job.fantasy}</p></div><div><small>ENTREGA</small><h3>{fmtDate(job.delivery)}</h3><p>{money.format(job.total)}</p></div></div><div className="blocks">{parseBlocks(job.work).map((b,i)=><article key={i}><span>TRABAJO {i+1}</span><h3>{field(b,`Archivo ${i+1}`)||field(b,'Archivo 1')||'Detalle de producción'}</h3><pre>{b}</pre></article>)}</div><SlideToFinish onDone={onFinish}/></Modal>}
function QuickPanel({mode,filter,setFilter,sort,setSort,last,close}){return <Modal title={mode==='filter'?'Filtrar panel':mode==='sort'?'Ordenar tarjetas':'Última importación'} onClose={close}>{mode==='filter'&&<div className="choice-list">{[['all','Todos'],['overdue','Atrasados'],['urgent','Urgentes'],['Pendiente','Pendientes'],['En proceso','En proceso'],['Falta información','Falta información']].map(([v,l])=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{l}<Check/></button>)}</div>}{mode==='sort'&&<div className="choice-list">{[['delivery','Fecha de entrega'],['priority','Prioridad'],['number','Número de orden'],['client','Cliente'],['created','Fecha de importación']].map(([v,l])=><button className={sort===v?'active':''} onClick={()=>setSort(v)} key={v}>{l}<Check/></button>)}</div>}{mode==='lastImport'&&(last?<div className="import-summary"><FileSpreadsheet/><h3>{last.name}</h3><p>Hoja: {last.sheet}</p><p>Leídos: {last.read} · Importados: {last.imported}</p><p>Duplicados: {last.duplicates}</p><p>{new Date(last.date).toLocaleString('es-AR')}</p></div>:<p>Todavía no se importó ningún archivo.</p>)}</Modal>}
